modLoader = "javafml"
loaderVersion = "[36,)"
license="MIT"
[[mods]]
    modId="exposer"
    version="${version}"
    displayName="Re-Exposer"
    authors = "Zengyj"
    description = '''
    Make RS item storage identifiable as a storage, such as a chest
    '''

[[dependencies.exposer]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exposer]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.exposer]]
    modId="refinedstorage"
    mandatory=true
    versionRange="[1.9.7,)"
    ordering="NONE"
    side="BOTH"